function PCIexport = func_importPCI(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   PCIADDS007TESTEXPORT = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   PCIADDS007TESTEXPORT = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   PCIADDS007testexport = importfile('PCI_ADDS_007_testexport.csv', 2, 18800);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/08/17 10:26:14

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,8,9,10,13,14,15]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,8,9,10,13,14,15]);
rawCellColumns = raw(:, [6,7,11,12,16]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
PCIexport = table;
PCIexport.framenum = cell2mat(rawNumericColumns(:, 1));
PCIexport.time = cell2mat(rawNumericColumns(:, 2));
PCIexport.babyobjordinal = cell2mat(rawNumericColumns(:, 3));
PCIexport.babyobjonset = cell2mat(rawNumericColumns(:, 4));
PCIexport.babyobjoffset = cell2mat(rawNumericColumns(:, 5));
PCIexport.babyobjcode01 = rawCellColumns(:, 1);
PCIexport.babyobjcode02 = rawCellColumns(:, 2);
PCIexport.parentobjordinal = cell2mat(rawNumericColumns(:, 6));
PCIexport.parentobjonset = cell2mat(rawNumericColumns(:, 7));
PCIexport.parentobjoffset = cell2mat(rawNumericColumns(:, 8));
PCIexport.parentobjcode01 = rawCellColumns(:, 3);
PCIexport.parentobjcode02 = rawCellColumns(:, 4);
PCIexport.commentsordinal = cell2mat(rawNumericColumns(:, 9));
PCIexport.commentsonset = cell2mat(rawNumericColumns(:, 10));
PCIexport.commentsoffset = cell2mat(rawNumericColumns(:, 11));
PCIexport.commentscode01 = rawCellColumns(:, 5);

